#!/bin/bash
#when modified, copy No+addons
while [ ! -f CHG ];do	#verrfy existence
      sleep 1s
done
cp CHG mirror_CHG
file=CHG
file2=mirror_CHG
i=0
while true
do
  rows=`wc -l $file | sed 's/CHG//g'|sed 's/ //g'` #cal row
  rowsadd=$rows+1
  old=`stat $file | grep -i Modify | awk -F. '{print $1}' | awk '{print $2$3}'|awk -F- '{print $1$2$3}' | awk -F: '{print $1$2$3}'`
  sleep 1s #pause for 1s
  new_old=`stat $file | grep -i Modify | awk -F. '{print $1}' | awk '{print $2$3}'|awk -F- '{print $1$2$3}' | awk -F: '{print $1$2$3}'`
  if [ $old -eq $new_old ]
  then
     continue
  else
     newrows=`wc -l $file | sed 's/CHG//g'|sed 's/ //g'`
     echo "aaaa$(($i))" >> $file2
     sed -n "$(($rowsadd)), $(($newrows))p" $file >>  $file2 #add changes
     i=$(($i+1))
  fi
done
